import "./global.css"; 
import Navbar from "./components/Navbar"; 
import Footer from "./components/Footer"; 
import "./lib/global"
import "./home.css";


export const metadata = {
  title: "Home",
  description: "Generated by create next app",
  
}; 

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />

        
        
      </body>
    </html>
  );
}
